//export const URL_BACKEND = 'https://soyjose.herokuapp.com'
export const URL_BACKEND = 'http://localhost:8090/api/socialweb'
//export const URL_BACKEND_OAUTH2 = 'https://soyjose-oauth2.herokuapp.com'
export const URL_BACKEND_OAUTH2 = 'http://localhost:8090/api/security'
//export const URL_BACKEND_ZUUL = 'https://soyjose-zuul.herokuapp.com'
export const URL_BACKEND_ZUUL = 'http://localhost:8090'